# site setup
exclude:
  - README.md
  - BUILD.md
  - .gitignore
  - LICENSE
permalink: /:title
markdown: kramdown
baseurl:
# course setup
title: "Fundamentals of Interactive and Data Journalism (IDJ)"
semester: "Fall 2016"
duration: "15 Weeks"
instructor:
 - Miguel Paz
coursecode:
 - "Thursday: JOURN71003 / CRN32328"
 - "Friday: JOURN71003 / CRN32331"
coursedates:
 - "Thursday class: August 25 to December 15, 2016. No classes on Thursday October 6 and Thursday November 24."
 - "Friday class: August 26 to December 16, 2016. No classes on Friday October 14 and Friday November 25."
coursetime: "9:30 am to 12:20 pm"
courselocation:
 - "Thursday: Rm 434"
 - "Friday: Rm 436"
communication:
 -
   name: "Email"
   description: "For questions, comments, class updates and sending copy of assignments"
   details: "miguel.paz@journalism.cuny.edu"
 -
   name: "SMS"
   description: "If itâ€™s urgent you can text me (no voice mail). I will get back to you asap"
   details: "123-234-5678"
 -
   name: "Slack"
   description: "We will use Slack if students agree to. Slack is a easy one to one, one to many, many to many team tool for work and play"
   details: "tbd"
officehours:
  description: "Thursdays and Fridays 3:00 pm to 5:00 pm at Office 421A. By appointment only."
  link: "https://calendly.com/miguelpaz/officehours"
# Tachyons Version
tv: "4.5.3"

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# SCSS Compress
sass:
  style: compressed